<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<RootNamespace>TorchUI</RootNamespace>

		<PackageId>TorchUI.Core</PackageId>
		<Title>TorchUI Core</Title>
		<PackageVersion>0.1.0</PackageVersion>
		<PackageReleaseNotes>Initial release</PackageReleaseNotes>
		<Authors>Christian LeVesque</Authors>
		<Description>
			Contains core utilities for creating Blazor Static SSR component libraries
		</Description>
		<PackageProjectUrl>https://torchui.com</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/christianlevesque/torch-ui</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>blazor torch ui torchui</PackageTags>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
		<None Include="./README.md" Pack="true" PackagePath="/"/>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.15"/>
		<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.9"/>
	</ItemGroup>

</Project>
